"""
PCB Design Export Functionality.

This module provides exporters for various PCB manufacturing formats:
- Gerber RS-274X format for PCB fabrication
- Bill of Materials (BOM) in multiple formats
- Pick and Place files for assembly
- 3D model export
"""

import csv
import io
import json
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum, auto
from typing import Any

from quantum_pcb_builder.core.pcb import PCBBoard, PCBLayer


class ExportFormat(Enum):
    """Supported export formats."""

    GERBER_274X = auto()
    EXCELLON = auto()
    BOM_CSV = auto()
    BOM_JSON = auto()
    PICK_PLACE = auto()
    ODB_PP = auto()


@dataclass
class ExportResult:
    """Result of an export operation."""

    success: bool
    format: ExportFormat
    files: dict[str, str] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


class Exporter(ABC):
    """Abstract base class for exporters."""

    @abstractmethod
    def export(self, board: PCBBoard) -> ExportResult:
        """Export board data."""


class GerberExporter(Exporter):
    """
    Gerber RS-274X format exporter.

    Generates industry-standard Gerber files for PCB fabrication.
    """

    def __init__(
        self,
        precision: int = 6,
        units: str = "mm",
        include_aperture_list: bool = True,
    ) -> None:
        """
        Initialize Gerber exporter.

        Args:
            precision: Decimal precision for coordinates
            units: Unit system ("mm" or "inch")
            include_aperture_list: Include aperture definitions in output
        """
        self.precision = precision
        self.units = units
        self.include_aperture_list = include_aperture_list

    def export(self, board: PCBBoard) -> ExportResult:
        """
        Export board to Gerber format.

        Args:
            board: PCB board to export

        Returns:
            ExportResult with generated files
        """
        files = {}
        errors = []
        warnings = []

        try:
            # Generate files for each layer
            layer_files = {
                PCBLayer.TOP_COPPER: f"{board.name}_Top_Cu.gbr",
                PCBLayer.BOTTOM_COPPER: f"{board.name}_Bottom_Cu.gbr",
                PCBLayer.TOP_SOLDER_MASK: f"{board.name}_Top_Mask.gbr",
                PCBLayer.BOTTOM_SOLDER_MASK: f"{board.name}_Bottom_Mask.gbr",
                PCBLayer.TOP_SILKSCREEN: f"{board.name}_Top_Silk.gbr",
                PCBLayer.EDGE_CUTS: f"{board.name}_Edge_Cuts.gbr",
            }

            for layer, filename in layer_files.items():
                content = self._generate_layer(board, layer)
                files[filename] = content

            # Generate drill file
            drill_content = self._generate_drill_file(board)
            files[f"{board.name}_Drill.drl"] = drill_content

        except Exception as e:
            errors.append(str(e))

        return ExportResult(
            success=len(errors) == 0,
            format=ExportFormat.GERBER_274X,
            files=files,
            errors=errors,
            warnings=warnings,
        )

    def _generate_layer(self, board: PCBBoard, layer: PCBLayer) -> str:
        """Generate Gerber content for a specific layer."""
        lines = []

        # Header
        lines.append("G04 Generated by Quantum PCB Builder*")
        lines.append(f"G04 Layer: {layer.name}*")
        lines.append(f"G04 Date: {datetime.now().isoformat()}*")
        lines.append("%FSLAX36Y36*%")
        lines.append(f"%MO{'MM' if self.units == 'mm' else 'IN'}*%")
        lines.append("%LPD*%")

        # Aperture definitions
        apertures = self._generate_apertures(board)
        lines.extend(apertures)

        # Layer content
        if layer == PCBLayer.EDGE_CUTS:
            lines.extend(self._generate_board_outline(board))
        elif layer in (PCBLayer.TOP_COPPER, PCBLayer.BOTTOM_COPPER):
            lines.extend(self._generate_copper_layer(board, layer))
        elif layer in (PCBLayer.TOP_SOLDER_MASK, PCBLayer.BOTTOM_SOLDER_MASK):
            lines.extend(self._generate_solder_mask(board, layer))
        elif layer == PCBLayer.TOP_SILKSCREEN:
            lines.extend(self._generate_silkscreen(board))

        # End of file
        lines.append("M02*")

        return "\n".join(lines)

    def _generate_apertures(self, board: PCBBoard) -> list[str]:
        """Generate aperture definitions."""
        apertures = []

        # Standard apertures
        apertures.append("%ADD10C,0.100*%")
        apertures.append("%ADD11C,0.150*%")
        apertures.append("%ADD12C,0.200*%")
        apertures.append("%ADD13C,0.250*%")
        apertures.append("%ADD14C,0.300*%")
        apertures.append("%ADD15R,1.000X1.000*%")
        apertures.append("%ADD16R,2.000X1.000*%")

        return apertures

    def _generate_board_outline(self, board: PCBBoard) -> list[str]:
        """Generate board outline."""
        lines = []
        lines.append("D10*")

        # Board rectangle
        x1 = self._format_coord(0)
        y1 = self._format_coord(0)
        x2 = self._format_coord(board.width_mm)
        y2 = self._format_coord(board.height_mm)

        lines.append(f"X{x1}Y{y1}D02*")
        lines.append(f"X{x2}Y{y1}D01*")
        lines.append(f"X{x2}Y{y2}D01*")
        lines.append(f"X{x1}Y{y2}D01*")
        lines.append(f"X{x1}Y{y1}D01*")

        return lines

    def _generate_copper_layer(self, board: PCBBoard, layer: PCBLayer) -> list[str]:
        """Generate copper layer content."""
        lines = []

        # Trace aperture
        lines.append("D13*")

        for trace in board.traces:
            if trace.layer == layer:
                x1 = self._format_coord(trace.start[0])
                y1 = self._format_coord(trace.start[1])
                x2 = self._format_coord(trace.end[0])
                y2 = self._format_coord(trace.end[1])

                lines.append(f"X{x1}Y{y1}D02*")
                lines.append(f"X{x2}Y{y2}D01*")

        # Component pads
        target_layer = "top" if layer == PCBLayer.TOP_COPPER else "bottom"
        lines.append("D15*")

        for component in board.components.values():
            if component.layer == target_layer:
                x = self._format_coord(component.position[0])
                y = self._format_coord(component.position[1])
                lines.append(f"X{x}Y{y}D03*")

        return lines

    def _generate_solder_mask(self, board: PCBBoard, layer: PCBLayer) -> list[str]:
        """Generate solder mask layer."""
        lines = []
        lines.append("D15*")

        target_layer = "top" if layer == PCBLayer.TOP_SOLDER_MASK else "bottom"

        for component in board.components.values():
            if component.layer == target_layer:
                x = self._format_coord(component.position[0])
                y = self._format_coord(component.position[1])
                lines.append(f"X{x}Y{y}D03*")

        return lines

    def _generate_silkscreen(self, board: PCBBoard) -> list[str]:
        """Generate silkscreen layer."""
        lines = []
        lines.append("D10*")

        for component in board.components.values():
            if component.layer == "top":
                bbox = component.get_bounding_box()
                x1 = self._format_coord(bbox[0])
                y1 = self._format_coord(bbox[1])
                x2 = self._format_coord(bbox[2])
                y2 = self._format_coord(bbox[3])

                lines.append(f"X{x1}Y{y1}D02*")
                lines.append(f"X{x2}Y{y1}D01*")
                lines.append(f"X{x2}Y{y2}D01*")
                lines.append(f"X{x1}Y{y2}D01*")
                lines.append(f"X{x1}Y{y1}D01*")

        return lines

    def _generate_drill_file(self, board: PCBBoard) -> str:
        """Generate Excellon drill file."""
        lines = []

        lines.append("; Generated by Quantum PCB Builder")
        lines.append(f"; Date: {datetime.now().isoformat()}")
        lines.append("M48")
        lines.append(f"{'METRIC' if self.units == 'mm' else 'INCH'},TZ")

        # Tool definitions
        tool_sizes = set()
        for via in board.vias:
            tool_sizes.add(via.drill_mm)

        tools = {}
        for i, size in enumerate(sorted(tool_sizes), start=1):
            tools[size] = f"T{i:02d}"
            lines.append(f"T{i:02d}C{size:.3f}")

        lines.append("%")

        # Drill locations
        for size in sorted(tool_sizes):
            lines.append(tools[size])
            for via in board.vias:
                if via.drill_mm == size:
                    x = via.position[0]
                    y = via.position[1]
                    lines.append(f"X{x:.3f}Y{y:.3f}")

        lines.append("M30")

        return "\n".join(lines)

    def _format_coord(self, value: float) -> str:
        """Format coordinate value for Gerber."""
        scaled = int(value * (10**self.precision))
        return str(scaled)


class BOMExporter(Exporter):
    """
    Bill of Materials exporter.

    Generates BOM in CSV or JSON format for procurement.
    """

    def __init__(
        self,
        format: ExportFormat = ExportFormat.BOM_CSV,
        include_prices: bool = True,
        group_by_value: bool = True,
    ) -> None:
        """
        Initialize BOM exporter.

        Args:
            format: Output format (BOM_CSV or BOM_JSON)
            include_prices: Include pricing information
            group_by_value: Group identical components
        """
        self.format = format
        self.include_prices = include_prices
        self.group_by_value = group_by_value

    def export(self, board: PCBBoard) -> ExportResult:
        """
        Export BOM from board.

        Args:
            board: PCB board to export BOM from

        Returns:
            ExportResult with BOM files
        """
        files = {}
        errors = []

        try:
            bom_data = self._generate_bom_data(board)

            if self.format == ExportFormat.BOM_CSV:
                content = self._to_csv(bom_data)
                files[f"{board.name}_BOM.csv"] = content
            else:
                content = self._to_json(bom_data)
                files[f"{board.name}_BOM.json"] = content

        except Exception as e:
            errors.append(str(e))

        return ExportResult(
            success=len(errors) == 0,
            format=self.format,
            files=files,
            errors=errors,
        )

    def _generate_bom_data(self, board: PCBBoard) -> list[dict[str, Any]]:
        """Generate BOM data from board components."""
        if self.group_by_value:
            return self._generate_grouped_bom(board)
        else:
            return self._generate_flat_bom(board)

    def _generate_flat_bom(self, board: PCBBoard) -> list[dict[str, Any]]:
        """Generate flat BOM with one entry per component."""
        bom = []

        for i, component in enumerate(board.components.values(), start=1):
            entry = {
                "item": i,
                "designator": component.name,
                "value": component.value,
                "package": component.package,
                "quantity": 1,
                "description": component.component_type.name,
            }
            bom.append(entry)

        return bom

    def _generate_grouped_bom(self, board: PCBBoard) -> list[dict[str, Any]]:
        """Generate grouped BOM consolidating identical components."""
        groups: dict[str, dict[str, Any]] = {}

        for component in board.components.values():
            key = f"{component.component_type.name}_{component.value}_{component.package}"

            if key not in groups:
                groups[key] = {
                    "designators": [],
                    "value": component.value,
                    "package": component.package,
                    "quantity": 0,
                    "description": component.component_type.name,
                }

            groups[key]["designators"].append(component.name)
            groups[key]["quantity"] += 1

        bom = []
        for i, (_, data) in enumerate(groups.items(), start=1):
            entry = {
                "item": i,
                "designators": ", ".join(data["designators"]),
                "value": data["value"],
                "package": data["package"],
                "quantity": data["quantity"],
                "description": data["description"],
            }
            bom.append(entry)

        return bom

    def _to_csv(self, bom_data: list[dict[str, Any]]) -> str:
        """Convert BOM data to CSV format."""
        if not bom_data:
            return ""

        output = io.StringIO()
        fieldnames = list(bom_data[0].keys())
        writer = csv.DictWriter(output, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(bom_data)

        return output.getvalue()

    def _to_json(self, bom_data: list[dict[str, Any]]) -> str:
        """Convert BOM data to JSON format."""
        return json.dumps(
            {
                "generated": datetime.now().isoformat(),
                "generator": "Quantum PCB Builder",
                "items": bom_data,
                "total_items": sum(item.get("quantity", 1) for item in bom_data),
            },
            indent=2,
        )


class PickPlaceExporter:
    """
    Pick and Place file exporter for automated assembly.
    """

    def __init__(self, units: str = "mm") -> None:
        """Initialize exporter with units."""
        self.units = units

    def export(self, board: PCBBoard) -> ExportResult:
        """
        Export pick and place file.

        Args:
            board: PCB board to export

        Returns:
            ExportResult with pick and place file
        """
        lines = []

        # Header
        lines.append("# Pick and Place File")
        lines.append(f"# Generated: {datetime.now().isoformat()}")
        lines.append(f"# Units: {self.units}")
        lines.append("#")
        lines.append("# Designator,X,Y,Rotation,Layer,Value,Package")

        # Component entries
        for component in board.components.values():
            x = component.position[0]
            y = component.position[1]
            rotation = component.rotation
            layer = component.layer
            value = component.value
            package = component.package

            line = f"{component.name},{x:.3f},{y:.3f},{rotation:.1f},{layer},{value},{package}"
            lines.append(line)

        content = "\n".join(lines)

        return ExportResult(
            success=True,
            format=ExportFormat.PICK_PLACE,
            files={f"{board.name}_PickPlace.csv": content},
        )
