"""Core module containing base classes, protocols, and utilities."""

from quantum_pcb_builder.core.base import (
    BaseComponent,
    BaseDesign,
    ValidationResult,
)
from quantum_pcb_builder.core.events import (
    Event,
    EventBus,
    EventHandler,
)
from quantum_pcb_builder.core.exceptions import (
    AIError,
    ComponentAlreadyExistsError,
    ComponentError,
    ComponentNotFoundError,
    ComponentValidationError,
    ConfigurationError,
    ConnectionError,
    DeserializationError,
    DesignError,
    DesignGenerationError,
    DesignLockedError,
    DesignNotFoundError,
    DesignValidationError,
    IncompatibleComponentsError,
    InvalidBidError,
    LayoutError,
    LayoutValidationError,
    ListingExpiredError,
    ListingNotFoundError,
    MarketplaceError,
    OptimizationError,
    OutOfBoundsError,
    PipelineError,
    PlacementError,
    QuantumPCBError,
    SerializationError,
    ValidationError,
    WorkflowError,
    WorkflowNotFoundError,
    WorkflowStepError,
)
from quantum_pcb_builder.core.factory import (
    ComponentBlueprint,
    ComponentBuilder,
    ComponentFactory,
    register_default_components,
)
from quantum_pcb_builder.core.logging import (
    ConsoleFormatter,
    LogContext,
    LoggerFactory,
    LogLevel,
    StructuredFormatter,
    get_logger,
)
from quantum_pcb_builder.core.protocols import (
    ComponentProtocol,
    DesignProtocol,
    MarketplaceProtocol,
    WorkflowProtocol,
)
from quantum_pcb_builder.core.quality import (
    DictValidator,
    NumberValidator,
    QualityAssuranceEngine,
    QualityLevel,
    QualityReport,
    Rule,
    RuleBasedValidator,
    StringValidator,
    Validator,
    ensure_valid,
)

__all__ = [
    # Protocols
    "ComponentProtocol",
    "DesignProtocol",
    "MarketplaceProtocol",
    "WorkflowProtocol",
    # Base classes
    "BaseComponent",
    "BaseDesign",
    "ValidationResult",
    # Events
    "Event",
    "EventBus",
    "EventHandler",
    # Exceptions
    "QuantumPCBError",
    "ValidationError",
    "ComponentValidationError",
    "DesignValidationError",
    "LayoutValidationError",
    "ComponentError",
    "ComponentNotFoundError",
    "ComponentAlreadyExistsError",
    "IncompatibleComponentsError",
    "DesignError",
    "DesignNotFoundError",
    "DesignLockedError",
    "LayoutError",
    "PlacementError",
    "OutOfBoundsError",
    "ConnectionError",
    "MarketplaceError",
    "ListingNotFoundError",
    "InvalidBidError",
    "ListingExpiredError",
    "WorkflowError",
    "WorkflowNotFoundError",
    "WorkflowStepError",
    "PipelineError",
    "AIError",
    "DesignGenerationError",
    "OptimizationError",
    "ConfigurationError",
    "SerializationError",
    "DeserializationError",
    # Factory
    "ComponentFactory",
    "ComponentBuilder",
    "ComponentBlueprint",
    "register_default_components",
    # Logging
    "LogLevel",
    "LoggerFactory",
    "ConsoleFormatter",
    "StructuredFormatter",
    "LogContext",
    "get_logger",
    # Quality
    "QualityLevel",
    "QualityReport",
    "Validator",
    "Rule",
    "RuleBasedValidator",
    "StringValidator",
    "NumberValidator",
    "DictValidator",
    "QualityAssuranceEngine",
    "ensure_valid",
]
